version: "3"
services:
    frontend:
        build: 
         context: .
        image: frontend
        container_name: frontend
        ports: 
            - "8080:80"
        networks:
            - intregrated-network
networks:
    intregrated-network:
       external: true