version: "3"
services:
    frontend:
        image: ghcr.io/skeletonbear/front-end:latest
        container_name: frontend
        # ports: 
        #     - "80:80"
        networks:
            - intregrated-network

networks:
    intregrated-network:
       external: true