version: "3"
services:
    frontend:
        image: ghcr.io/skeletonbear/front-end:latest
        container_name: frontend
        # ports: 
        #     - "80:80"
        networks:
            - intregrated-network:
                ipv4_address: 172.18.0.4
networks:
    default:
        external:
            name: intregrated-network
    intregrated-network:
       external: true